import { initDb, getAllBatteries, getMeasurementsByBatteryId, getSettings, saveBattery, deleteBattery, saveMeasurement, deleteMeasurement, deleteMeasurementsByBatteryId } from "./db.js";
import { archiveBattery, createBattery, restoreBattery } from "./battery.js";
import { createChargeMeasurement, createLedMeasurement, createPercentageMeasurement, updateMeasurement } from "./measurement.js";
import { calculateBatteryStatus } from "./calculation.js";
import { renderDashboard, renderAllBatteries, renderArchives, renderBatteryDetails, openBatteryFormModal, openMeasurementFormModal, openQuickMeasurementPicker, openSideMenu } from "./ui.js";
import { downloadJsonBackup } from "./import-export.js";
import { INPUT_MODES, VIEWS } from "./constants.js";

let state = { batteries: [], settings: null, statuses: [], currentView: VIEWS.HOME, currentBatteryId: null };
async function main(){ await initDb(); await reloadState(); renderHome(); document.querySelector("#floating-action-button").addEventListener("click", handleFabClick); document.querySelector("#menu-button").addEventListener("click",()=>openSideMenu({ onHome:renderHome, onAllBatteries:renderAllBatteriesView, onCreateBattery:()=>openBatteryFormModal({onSave:handleCreateBattery}), onArchives:renderArchivesView, onExportJson:handleExportJson, onSettings:()=>alert("Paramètres : prévu dans la prochaine itération.") })); }
async function reloadState(){ state.settings=await getSettings(); state.batteries=(await getAllBatteries()).map(b=>createBattery(b)); state.statuses=[]; for(const battery of state.batteries){ const measurements=await getMeasurementsByBatteryId(battery.id); state.statuses.push({ battery, status: calculateBatteryStatus(battery, measurements, state.settings) }); } }
function setView(view,batteryId=null){ state.currentView=view; state.currentBatteryId=batteryId; }
function renderHome(){ setView(VIEWS.HOME); renderDashboard(state.statuses,{ onShowAll:renderAllBatteriesView, onOpenBattery:openBatteryDetails }); }
function renderAllBatteriesView(){ setView(VIEWS.ALL_BATTERIES); renderAllBatteries(state.statuses,{ onOpenBattery:openBatteryDetails }); }
function renderArchivesView(){ setView(VIEWS.ARCHIVES); renderArchives(state.statuses,{ onOpenBattery:openBatteryDetails }); }
async function openBatteryDetails(batteryId){ setView(VIEWS.BATTERY_DETAILS,batteryId); const battery=state.batteries.find(b=>b.id===batteryId); const measurements=await getMeasurementsByBatteryId(batteryId); const status=calculateBatteryStatus(battery,measurements,state.settings); renderBatteryDetails(battery,measurements,status,{ onAddCharge:handleAddCharge, onEditMeasurement:(id)=>handleEditMeasurement(battery,id), onArchiveBattery:handleArchiveBattery, onRestoreBattery:handleRestoreBattery, onDeleteBattery:handleDeleteBattery }); }
async function handleFabClick(){ if(state.currentView===VIEWS.ALL_BATTERIES){ openBatteryFormModal({onSave:handleCreateBattery}); return; } if(state.currentView===VIEWS.BATTERY_DETAILS && state.currentBatteryId){ const battery=state.batteries.find(b=>b.id===state.currentBatteryId); openMeasurementFormModal(battery,null,{ onSave:async data=>handleCreateMeasurement(battery,data) }); return; } openQuickMeasurementPicker(state.statuses,{ onSelectBattery:battery=>openMeasurementFormModal(battery,null,{ onSave:async data=>handleCreateMeasurement(battery,data) }) }); }
async function handleCreateBattery(data){ const battery=createBattery(data); await saveBattery(battery); await reloadState(); renderAllBatteriesView(); }
async function handleCreateMeasurement(battery,data){ const m=battery.preferredInputMode===INPUT_MODES.LED && battery.ledConfig ? createLedMeasurement({ batteryId:battery.id, ledCount:battery.ledConfig.ledCount, behavior:battery.ledConfig.behavior, sliderPosition:data.sliderPosition, levelPercent:data.levelPercent, date:data.date }) : createPercentageMeasurement({ batteryId:battery.id, levelPercent:data.levelPercent, date:data.date }); await saveMeasurement(m); await reloadState(); await openBatteryDetails(battery.id); }
async function handleAddCharge(batteryId){ await saveMeasurement(createChargeMeasurement(batteryId)); await reloadState(); await openBatteryDetails(batteryId); }
async function handleEditMeasurement(battery, measurementId){ const measurements=await getMeasurementsByBatteryId(battery.id); const measurement=measurements.find(m=>m.id===measurementId); if(!measurement) return; openMeasurementFormModal(battery,measurement,{ onSave:async data=>{ let updated; if(measurement.observation?.mode===INPUT_MODES.LED){ const obs=measurement.observation; const temp=createLedMeasurement({ batteryId:battery.id, ledCount:obs.ledCount, behavior:obs.behavior, sliderPosition:data.sliderPosition, levelPercent:data.levelPercent, date:data.date }); updated=updateMeasurement(measurement,{ date:temp.date, levelPercent:temp.levelPercent, source:temp.source, observation:temp.observation }); } else { updated=updateMeasurement(measurement,{ date:data.date, levelPercent:data.levelPercent, observation:{ mode:INPUT_MODES.PERCENTAGE, value:data.levelPercent } }); } await saveMeasurement(updated); await reloadState(); await openBatteryDetails(battery.id); }, onDelete:async()=>{ await deleteMeasurement(measurement.id); await reloadState(); await openBatteryDetails(battery.id); } }); }
async function handleArchiveBattery(battery){ if(!confirm(`Archiver ${battery.name} ?`)) return; await saveBattery(archiveBattery(battery)); await reloadState(); renderHome(); }
async function handleRestoreBattery(battery){ await saveBattery(restoreBattery(battery)); await reloadState(); await openBatteryDetails(battery.id); }
async function handleDeleteBattery(battery){ if(!confirm(`Supprimer définitivement ${battery.name} et toutes ses mesures ?`)) return; await deleteMeasurementsByBatteryId(battery.id); await deleteBattery(battery.id); await reloadState(); renderHome(); }
async function handleExportJson(){ await downloadJsonBackup(); }
main().catch(error=>{ console.error(error); document.querySelector("#app").innerHTML=`<section class="card"><h2>Erreur</h2><p>${error.message}</p></section>`; });
